name: "Yassine Ayouch"
description: "blog"
meta_description: "[blog] by Yassine Ayouch"
gems: [jekyll-paginate]

aboutPage: true

markdown: kramdown
highlighter: rouge

paginate: 20
baseurl: /
domain_name: 'https://blog.ayouch.me'
google_analytics: 'empty'
disqus: true
disqus_shortname: 'yassineayouch'

# Details for the RSS feed generator
url:            'https://blog.ayouch.me'
author:         'Yassine Ayouch'
authorTwitter:  'yassineayouch'

permalink:       /:year/:month/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
